LIB=-lgtest -lgtest_main -lgmock

Defining_a_Mock_Class: Defining_a_Mock_Class.cpp
	g++ Defining_a_Mock_Class.cpp $(LIB)
	./a.out

Using_Mocks_in_Tests:  Using_Mocks_in_Tests.cpp
	g++ Using_Mocks_in_Tests.cpp $(LIB)
	./a.out
